apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:                 #define os o conteúdo do arquivo, pois não há inspect como os demais recursos
  MYSQL_ROOT_PASSWORD: q1w2e3r4
  MYSQL_DATABASE: empresa
  MYSQL_PASSWORD: q1w2e3r4