apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  template:         #coloca o Pod que ficará dentro do Replica Set
    metadata: portal-noticias
    labels:
      app: portal-noticias
  spec:
    containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-noticias-configmap
  replicas: 3     #avisa o número de replicas que deseja, por padrão ele tem 1 replica
  selector:       #avisa para selecionar os recursos abaixos
    matchLabels:  #ele tem que ser o mesmo do Labels acima ou não funciona
      app: portal-noticias          