apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-replicaset
spec:
  template:         
    metadata: portal-noticias
    labels:
      app: portal-noticias
  spec:
    containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-noticias-configmap
      livenessProbe:              ####ADIÇÃO DO LIVENESS PROBES####
        httpGet:
          path: /
          port: 80
        periodSeconds: 10         #período de tempo que testerá
        failureThreshold: 3       #quantidades de falhas esperada para reiniciar
        initialDelaySeconds: 20   #tempo de espera ao reiniciar para voltar a testar
      readinessProbe:              
        httpGet:
          path: /inserir_noticias.php
          port: 80
        periodSeconds: 10        
        failureThreshold: 5       
        initialDelaySeconds: 3  
      resources:
        requests:
          cpu: 10m
  replicas: 3     
  selector:       
    matchLabels:  
      app: portal-noticias          